### PR TITLE
Fixed script for ubuntu amd64 distribution

### PR DESCRIPTION
**Pull request by jjponz**
Hello:

The script to install seafile community-edition in ubuntu amd 64 have some fails that i fixed to solve the problems, and i modified the IP_OR_DOMAIN, instead of the ip, i use the hostname.

Cheers.

### CODE REVIEW

**Comment by shoeper** [comment]
Thanks, but having a short look at this looks like we shouldn't merge it.

Seahub settings doesn't need 0700. Furthermore you removed some variable. A proper fix should address the root cause which is likely to be the config layout change in 5.x.

**Comment by jjponz** [comment]
If i try to deploy seafile with the permissions 0600, and I don't put the file in the folder that indicate the manual, seafile not run.

Where are documented that the permissions are 0700?, i don't see this.

My system is Ubuntu 14.04.3 amd64.

**Comment by shoeper** [comment]
> Where are documented that the permissions are 0700?, i don't see this.

?

**Comment by jjponz** [comment]
Sorry,  the question is where are documented than permissions are 0600?

**Comment by shoeper** [comment]
Why does that need to be documented? Those are just file permissions and nothing special.

Because the script did work very well with v4 0600 is definitly enough.

Thanks for the PR, but I close this because it won't fix the existing problems properly.

**Pull request closed without merging**
